### ISSUE TITLE
landscape-intro and UA

### ISSUE THREAD

**Issue by pmatulis** [canonical-docs/landscape-docs#23]
On page [landscape-intro.md](https://github.com/CanonicalLtd/docs-landscape/blob/master/en/landscape-intro.md) the 'Ubuntu Advantage' paragraph is overdone. It can be replaced by a single link in the previous paragraph to:

https://www.ubuntu.com/support

instead of directly to the store.

**Comment by BryanQuigley** [comment]
We greatly redid the landing page and fixed this as part of it.
