### ISSUE TITLE
https://docs.ubuntu.com/landscape/en/landscape-api url is broken

### ISSUE THREAD

**Issue by lborda** [canonical-docs/landscape-docs#82]
Reproduce steps:

1. open https://docs.ubuntu.com/landscape/en/landscape-api

**Comment by alexmcan** [comment]
Where is the page that contains that broken link?

**Comment by lborda** [comment]
Reproduce steps:
1. open https://docs.ubuntu.com/landscape/en/landscape-api
404 error

**Comment by cjohnston1158** [comment]
https://docs.ubuntu.com/landscape/en/api is the correct location. Does something link to the URL you are trying?

**Comment by lborda** [comment]
sorry
1. go to https://docs.ubuntu.com/landscape/en/
2. search for "api" in the search box (first result will fail)

**Comment by nottrobin** [comment]
Will be fixed by https://github.com/canonical-websites/docs.ubuntu.com/pull/207
